package com.redhat.waw.bpm;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(6d7c404b4891fa451224c953c1dbd6f0)
 */
@org.kie.api.definition.type.Label(value = "Number Port Request")
public class NumberPortRequest extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer customerid;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.Date date;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String firstname;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String lastname;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigInteger number;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String status;

    public NumberPortRequest() {
    }

    public NumberPortRequest(java.lang.Integer customerid, java.math.BigInteger number, java.lang.String firstname, java.lang.String lastname, java.util.Date date, java.lang.String status) {
        this.customerid = customerid;
        this.number = number;
        this.firstname = firstname;
        this.lastname = lastname;
        this.date = date;
        this.status = status;
    }


    
    public java.lang.Integer getCustomerid() {
        return this.customerid;
    }

    public void setCustomerid(java.lang.Integer customerid) {
        this.customerid = customerid;
    }
    
    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }
    
    public java.lang.String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(java.lang.String firstname) {
        this.firstname = firstname;
    }
    
    public java.lang.String getLastname() {
        return this.lastname;
    }

    public void setLastname(java.lang.String lastname) {
        this.lastname = lastname;
    }
    
    public java.math.BigInteger getNumber() {
        return this.number;
    }

    public void setNumber(java.math.BigInteger number) {
        this.number = number;
    }
    
    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }
}