import java.util.Calendar;
import java.util.Date;
import com.redhat.waw.bpm.NumberPortRequest;

//declare any global variables here

function Date inOneMonth() {
    Calendar now = Calendar.getInstance();
    now.add(Calendar.MONTH, 1);    
    Date inOneMonth = now.getTime();
    System.out.println("In one month: " + inOneMonth);
    return inOneMonth;
}

rule "Valid date"

    ruleflow-group "validate"

    when
        request : NumberPortRequest( date.after(inOneMonth()) )
    then
        request.setStatus("validated");
        System.out.println("Executed Rule: " + drools.getRule().getName() );

end

rule "Invalid date"

    ruleflow-group "validate"

    when
        request : NumberPortRequest( date.before(inOneMonth()) )
    then
        request.setStatus("invalid");
        System.out.println("Executed Rule: " + drools.getRule().getName() );

end

rule "Retract request after validation"
	dialect "mvel"
	ruleflow-group "validate"
	salience -10
	when
		request : NumberPortRequest(  )
	then
		retract(request);
		System.out.println("Executed Rule: " + drools.getRule().getName() );
end