import java.util.Date;
import java.util.Calendar;
import com.redhat.waw.bpm.NumberPortRequest;

//declare any global variables here

function int daysFromNow(Date inDate) {
    System.out.println(inDate + " " + inDate.getTime() + " " + Calendar.getInstance().getTime() + " " + Calendar.getInstance().getTimeInMillis());
    return (int)((inDate.getTime() - Calendar.getInstance().getTimeInMillis()) / (24 * 60 * 60 * 1000));
}

rule "Valid date"
    dialect "mvel"
    ruleflow-group "validate"

    when
        request : NumberPortRequest( daysFromNow(date) >= 30 )
    then
        request.setStatus("validated");
        System.out.println("Executed Rule: " + drools.getRule().getName() + ":  " + request.getDate() + " is " +  daysFromNow(request.getDate()) + " days from now");
end

rule "Invalid date"
    dialect "mvel"
    ruleflow-group "validate"

    when
        request : NumberPortRequest( daysFromNow(date) < 30 )
    then
        request.setStatus("invalid");
        System.out.println("Executed Rule: " + drools.getRule().getName() + ": " + request.getDate() + " is " +  daysFromNow(request.getDate()) + " days from now");

end

rule "Retract request after validation"
	dialect "mvel"
	ruleflow-group "validate"
	salience -10
	when
		request : NumberPortRequest(  )
	then
		retract(request);
		System.out.println("Executed Rule: " + drools.getRule().getName() );
end